CREATE TABLE PERSONA (
    ID integer NOT NULL,
    AÑO_NACIMENTO character varying(100)
);

INSERT INTO PERSONA VALUES (991, '1999');
INSERT INTO PERSONA VALUES (992, '2002');



ALTER TABLE PERSONA
    ADD CONSTRAINT PERSONA_pkey PRIMARY KEY (ID);



